### PR TITLE
Braintree shield

### PR DESCRIPTION
**Pull request by peppeocchi**
Ref #4

### CODE REVIEW

**Comment by clarkeash** [comment]
Thanks for your contribution 😄

**Comment by clarkeash** [comment]
I have decided to create laravel-shield as an organisation, as putting all these services into one package especially as some have dependencies doesn't make much sense.

See here: http://laravel-shield.com/contributing and here: https://github.com/laravel-shield

Would you be willing to contribute to that project? The interface is slightly different but most of the code you should be able to copy & paste across.

If you are willing/have time then I will create you a repository to commit to.

**Comment by peppeocchi** [comment]
@clarkeash I agree, it's a much flexible solution and it make sense.

Sure thing I'll contribute.

**Comment by clarkeash** [comment]
Great I have created a project here: https://github.com/laravel-shield/braintree
You will need to accept an invite here: https://github.com/laravel-shield/braintree/invitations

I have started the project with some scaffolding, you will need to update the composer.json and class names etc.

**Comment by clarkeash** [comment]
Any discussions can take place here: https://github.com/laravel-shield/internals (just create a new issue) 😄

**Pull request merged**
