### PR TITLE
Implement travis ci

### LINKED ISSUE #3: [New Service] Travis CI
Docs: https://docs.travis-ci.com/user/notifications/#Verifying-Webhook-requests

### PR DESCRIPTION
**Pull request by tomodutch**
Fixes #3 

I've implement travis CI according to their [documentation](https://docs.travis-ci.com/user/notifications/#Verifying-Webhook-requests).

### CODE REVIEW

**Comment by tomodutch** [comment]
The build seems to have failed because of Codecov. Does it fail because the complexity of the code went up? If so, can you give me a pointer as to which piece of code in the commit contributes to the complexity. I can't find it within the report. Can it be the two if-statements on TravisCI.php line 35 and 41?

**Comment by clarkeash** [comment]
Dont worry about codecov, its too strict atm I will fix that. I need to check over the code before I merge this, I will try and do it this weekend but if I dont get to it then it maybe a couple of weeks as I will be on holiday/travelling etc.

**Comment by clarkeash** [comment]
Hi, I am not sure about this, I think we should use guzzle instead of `file_get_contents`.

**Comment by clarkeash** [comment]
I am closing this, if you wish to add travis you can you do it over here: http://laravel-shield.com/contributing

**Pull request closed without merging**
