### PR TITLE
Add shopify

### PR DESCRIPTION
**Pull request by TheAlexLichter**
Add a protection for Shopify webhooks!

Webhook signature info can be found [here](https://help.shopify.com/api/getting-started/webhooks).

### CODE REVIEW

**Comment by clarkeash** [comment]
I need to check over the code before I merge this, but from a quick glance it looks good, it maybe a couple of weeks as I soon will be on holiday/travelling etc. I might be able to get to it this weekend but no guarantees.

**Comment by clarkeash** [comment]
I have decided to create laravel-shield as an organisation, as putting all these services into one package especially as some have dependencies doesn't make much sense.

See here: http://laravel-shield.com/contributing and here: https://github.com/laravel-shield

Would you be willing to contribute to that project? The interface is slightly different but most of the code you should be able to copy & paste across.

If you are willing/have time then I will create you a repository to commit to.

**Comment by TheAlexLichter** [comment]
Sure @clarkeash, I'm looking forward to it!

**Comment by clarkeash** [comment]
Great, I’ll sort this out tomorrow.

**Comment by clarkeash** [comment]
I have created a project here: https://github.com/laravel-shield/shopify
You will need to accept an invite here: https://github.com/laravel-shield/shopify/invitations

I have started the project with some scaffolding, you will need to update the composer.json and class names etc.

**Comment by clarkeash** [comment]
I am going to close this PR. Any discussions can take place here: https://github.com/laravel-shield/internals (just create a new issue) 😄

**Pull request closed without merging**
